// Code generated by goctl. DO NOT EDIT!
// Source: sms.proto

package server

import (
	"context"

	"go-zero-chat/apps/sms/internal/logic"
	"go-zero-chat/apps/sms/internal/svc"
	"go-zero-chat/apps/sms/sms"
)

type SmsServer struct {
	svcCtx *svc.ServiceContext
	sms.UnimplementedSmsServer
}

func NewSmsServer(svcCtx *svc.ServiceContext) *SmsServer {
	return &SmsServer{
		svcCtx: svcCtx,
	}
}

func (s *SmsServer) SendSms(ctx context.Context, in *sms.SendSmsReq) (*sms.SendSmsResp, error) {
	l := logic.NewSendSmsLogic(ctx, s.svcCtx)
	return l.SendSms(in)
}
